version: '3.8'

services:
  spotify-kiosk1:
    image: spearg/spotifydisplay:latest
    container_name: spotify-kiosk1
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
    networks:
      - default

networks:
  default:
    driver: bridge
